language: go
before_script:
- go get -u -v github.com/spf13/hugo
script:
- hugo --theme vienna -v
- mv .boto ~/
deploy:
  provider: s3
  access_key_id:
    secure: jFyaGQTFJQF1tiN3v/XQZVE7U3aW4Keat3kElQFM6LSO/gSGyAMU0hsKkQBs9TJ9cZJfeHyqtvZWpI6IPCobsV4aGE3Gp80dMMWu2heUiblWKpqopHcNOZwp3mJkXm61weJ2F2blBnjEKgcJQHEUWH/81BGigBnRkeoseGCjsXoZfPWLBxvjYWMUP8imR5c3ugAD5Z0AKfmWaal0Wt7Spw2SNWsAn/15v7rgNzo+YmGD9HKNXfjzMqkMcYhtfK+4Q1pmP/4LKX5zOBrKKoHh9WGjSZxhpJne06B8bHd7OxQVvjSW5AK5ykU8wh6Zi3y1blPUfpfmEYBMHmF1nw4JicQ/oxp1fw23RCnEdCqmk9XwTL/O0YaHOteH5ffM6hV7NkHcTdWq2DEU32QEQp7pzR7aFT/3qJDy3j+ovv4F3K2Vx8CjxJd7MXfKlmqvjVelApZpx3m9gi7KwpFWp6hGvgPtuZ8Wf1zECC/S5jvQGTuxm+Wd4hZrs1yjFmzHZQM1gr4FC4Qmn2pHdRsRw6daJxlUFpBkY7VxWUFiAy+jnxvfA/SD1lgDttU7STuPH0h0vS+Jxn03Q72StYtU7ZvME3d6SUMqWn/m0zwjqDnsAOogOAttCdn73RacWO2s4j9fc1i7PfRk5G1RDYgvJ+YudqY/wbRs+XSbbhO7iUTy6Vk=
  secret_access_key:
    secure: MykPks1iaCLHU88fooTJMKuj11+borQyiyzRBQQOeOGc6wUFXWS3eT90BSqL9aKV4iFucJ+gmUAexAaE7MD3z2kQybz8cps+HgsXAjbd1G5KYovP1GYQJBffieIewq85lK8FAEbCpM29cMkFNEekOnXPjyNhTegicQSyZWalX3wenQsnSnHY72nDspS5WCMzZhfrvK+dSyOd3Xxb08UKusHurMTfALNs+89CqLQgmQEkznvG1u+0Fen1OYIHGTAyKSxlL6ZAQCFPXPn8pOcGShPz9fpcBR6RIVBB4scETIB38Ii58SUfbH3Ju/UzxAvj19Ug/+ByHPy5lVlzxKeXskc6epUZi4U54GPFjncRMS0qnDrPKRu/bKsurEXX36FyZLQMUFyB474Fg93fbro/xnMi9VBch3G4jC78yzd8mGgiK51ZOQTZahg3vkRcC4fREJEiFK+vXKElILu2B4uk2WoNjGb0mxg87gpO025zOvHmiF9kQyW84A5vT+JgtuPxdMeARz74uHELib2F2dDW38paAhjXCXU3BrBzkvuOJTnYjzKh521gUpD9BMVmbbbFloFwr96Dovk5G84vjS+8g+/LL8xZjd6n6l9U1GX0o6IIx9m13lJzHE76WvltB4PYuLL34PSEcFj/jj6dpiYZK+uk9TXwe2RojKlv13slmW0=
  bucket: staging.bentley.blog
  local_dir: public
  region: us-east-1
  on:
    branch: master

