language: go
before_script:
- go get -u -v github.com/spf13/hugo
script:
- hugo --theme vienna -v
deploy:
  provider: s3
  access_key_id: AKIAI4UZ4LBMFLDFZ7UA
  secret_access_key:
    secure: MykPks1iaCLHU88fooTJMKuj11+borQyiyzRBQQOeOGc6wUFXWS3eT90BSqL9aKV4iFucJ+gmUAexAaE7MD3z2kQybz8cps+HgsXAjbd1G5KYovP1GYQJBffieIewq85lK8FAEbCpM29cMkFNEekOnXPjyNhTegicQSyZWalX3wenQsnSnHY72nDspS5WCMzZhfrvK+dSyOd3Xxb08UKusHurMTfALNs+89CqLQgmQEkznvG1u+0Fen1OYIHGTAyKSxlL6ZAQCFPXPn8pOcGShPz9fpcBR6RIVBB4scETIB38Ii58SUfbH3Ju/UzxAvj19Ug/+ByHPy5lVlzxKeXskc6epUZi4U54GPFjncRMS0qnDrPKRu/bKsurEXX36FyZLQMUFyB474Fg93fbro/xnMi9VBch3G4jC78yzd8mGgiK51ZOQTZahg3vkRcC4fREJEiFK+vXKElILu2B4uk2WoNjGb0mxg87gpO025zOvHmiF9kQyW84A5vT+JgtuPxdMeARz74uHELib2F2dDW38paAhjXCXU3BrBzkvuOJTnYjzKh521gUpD9BMVmbbbFloFwr96Dovk5G84vjS+8g+/LL8xZjd6n6l9U1GX0o6IIx9m13lJzHE76WvltB4PYuLL34PSEcFj/jj6dpiYZK+uk9TXwe2RojKlv13slmW0=
  bucket: staging.bentley.blog
  local_dir: public
  region: us-east-1
  on:
    branch: master

