baseurl = "http://test.mtb.wtf/"
languageCode = "en-us"
title = "Matthew Bentley"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."

[params]
    subtitle = "Just my blog"
    author = "Matthew Bentley"
    twitter = "matteotom"
    github = "matthewbentley"
    ga_api_key = "UA-41411412-2"
    avatar = "/avatar.jpg"
    bio = "Matthew is a student at Case Western Reserve University, where he is an executive member of Hacker Society and Undergraduate Student Government.  He spends most of his time either at school in Cleveland or at coffee shops in Seattle."
    contact = "mailto:matthew@bentley.link"
    theme = "vienna"
