#baseurl = "https://bentley.link/"
baseurl = "/"
languageCode = "en-us"
title = "Matthew Bentley"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."

[params]
    subtitle = "Just my blog"
    author = "Matthew Bentley"
    twitter = "matteotom"
    github = "matthewbentley"
    ga_api_key = "UA-41411412-2"
    avatar = "/avatar.jpg"
    bio = "I am a student at Case Western Reserve University. I'm currently working in London, UK for Yelp through November 2017."
    contact = "mailto:matthew@bentley.link"
    theme = "vienna"
